<?php

/*
 * Search-intent pages are deliberately kept separate from the CMS service
 * descriptions. Each page has its own problem framing and decision-stage copy,
 * while the CMS remains the source for the service index and admin editing.
 */
return [
    'pages' => [
        'custom-software-development' => [
            'id' => [
                'meta_title' => 'Jasa Pembuatan Software Custom untuk Perusahaan | Aldef Tech',
                'meta_description' => 'Jasa pembuatan software custom untuk menyatukan proses kerja, data, dan kontrol akses perusahaan dalam sistem yang sesuai kebutuhan.',
                'eyebrow' => 'Custom Software Development',
                'title' => 'Sistem custom untuk proses bisnis yang tidak bisa dipaksa seragam.',
                'accent' => 'Dibangun tepat sasaran.',
                'lead' => 'Aldef Tech membantu perusahaan memetakan proses, merancang arsitektur, dan membangun software custom yang dapat dikembangkan bersama bisnis.',
                'pain_points' => ['Data tersebar di spreadsheet dan aplikasi yang tidak saling berbicara.', 'Alur approval dan pekerjaan berulang sulit diawasi.', 'Software siap pakai tidak mengikuti aturan bisnis yang spesifik.'],
                'capabilities' => ['Analisis proses dan kebutuhan pengguna', 'Arsitektur aplikasi, database, dan API', 'Role-based access, audit trail, dan workflow', 'Pengujian, deployment, serta dokumentasi teknis'],
                'benefits' => ['Tim bekerja dengan alur yang lebih konsisten', 'Informasi operasional lebih mudah ditelusuri', 'Modul dapat dikembangkan mengikuti prioritas bisnis', 'Kepemilikan kode dan keputusan arsitektur tetap jelas'],
                'process' => ['Discovery: memahami pengguna, data, dan aturan bisnis', 'Blueprint: menyusun ruang lingkup dan prioritas modul', 'Build: pengembangan bertahap dengan review berkala', 'Handover: pengujian, rilis, dokumentasi, dan pendampingan'],
                'technologies' => ['Laravel / PHP', 'Node.js atau Python', 'Vue.js / React', 'PostgreSQL / MySQL', 'REST API dan Redis'],
                'faq' => [['q' => 'Kapan perusahaan membutuhkan software custom?', 'a' => 'Saat proses inti memiliki aturan, peran, atau integrasi yang tidak terakomodasi dengan baik oleh produk umum.'], ['q' => 'Apakah harus membangun seluruh sistem sekaligus?', 'a' => 'Tidak. Ruang lingkup dapat diprioritaskan agar modul paling penting dipahami dan diuji lebih dahulu.'], ['q' => 'Apa yang perlu disiapkan sebelum konsultasi?', 'a' => 'Cukup gambaran proses yang paling menghambat, pengguna yang terlibat, dan sistem yang sudah digunakan.']],
                'portfolio_terms' => ['POS', 'System', 'ERP', 'Dashboard'],
            ],
            'en' => [
                'meta_title' => 'Custom Software Development for Companies | Aldef Tech',
                'meta_description' => 'Custom software development that brings your company processes, data, permissions, and workflows into one adaptable system.',
                'eyebrow' => 'Custom Software Development', 'title' => 'Software shaped around the way your business actually works.', 'accent' => 'Built with intent.',
                'lead' => 'Aldef Tech maps the process, designs the architecture, and builds custom software that can evolve with your business.',
                'pain_points' => ['Data lives across spreadsheets and disconnected tools.', 'Approvals and repetitive work are difficult to oversee.', 'Off-the-shelf software cannot express your specific rules.'],
                'capabilities' => ['Process and user discovery', 'Application, database, and API architecture', 'Roles, audit trails, and workflow design', 'Testing, deployment, and technical documentation'],
                'benefits' => ['More consistent operating workflows', 'Traceable operational information', 'Modules that follow changing priorities', 'Clear ownership of code and architecture'],
                'process' => ['Discover: understand users, data, and rules', 'Blueprint: agree scope and module priorities', 'Build: develop in stages with regular reviews', 'Handover: test, release, document, and support'],
                'technologies' => ['Laravel / PHP', 'Node.js or Python', 'Vue.js / React', 'PostgreSQL / MySQL', 'REST APIs and Redis'],
                'faq' => [['q' => 'When does a company need custom software?', 'a' => 'When core processes have rules, roles, or integrations that general products cannot accommodate well.'], ['q' => 'Does everything need to be built at once?', 'a' => 'No. Scope can be prioritised so the most important module is understood and tested first.'], ['q' => 'What should we prepare for a consultation?', 'a' => 'A description of the most painful process, the people involved, and the systems already in use.']],
                'portfolio_terms' => ['POS', 'System', 'ERP', 'Dashboard'],
            ],
        ],
        'web-application' => [
            'id' => [
                'meta_title' => 'Jasa Aplikasi Web untuk Operasional Bisnis | Aldef Tech',
                'meta_description' => 'Jasa aplikasi web yang responsif dan terukur untuk portal internal, dashboard operasional, layanan pelanggan, dan proses bisnis perusahaan.',
                'eyebrow' => 'Web Application', 'title' => 'Aplikasi web yang membuat proses kerja lebih mudah diakses.', 'accent' => 'Dari browser.',
                'lead' => 'Bangun portal, dashboard, atau aplikasi operasional yang nyaman digunakan di desktop maupun mobile tanpa menambah friksi bagi tim.',
                'pain_points' => ['Aplikasi internal sulit dipakai saat tim bekerja mobile.', 'Informasi penting membutuhkan terlalu banyak langkah untuk ditemukan.', 'Pengalaman pengguna tidak konsisten antar perangkat.'],
                'capabilities' => ['UX flow dan interface responsif', 'Dashboard berbasis peran', 'API-first backend dan integrasi data', 'Performance, security, dan observability dasar'],
                'benefits' => ['Akses kerja yang lebih fleksibel', 'Navigasi yang lebih jelas bagi tiap peran', 'Ruang untuk integrasi dan otomasi lanjutan', 'Fondasi web yang mudah dirawat'],
                'process' => ['Pahami konteks pengguna dan perangkat', 'Rancang flow utama serta struktur data', 'Bangun komponen inti dan integrasi', 'Uji pada skenario nyata lalu rilis bertahap'],
                'technologies' => ['Laravel / PHP', 'Vue.js / React', 'Tailwind CSS', 'PostgreSQL / MySQL', 'REST / GraphQL'],
                'faq' => [['q' => 'Apakah aplikasi web bisa menggantikan aplikasi desktop?', 'a' => 'Untuk banyak proses bisnis, aplikasi web dapat menjadi pilihan yang lebih mudah dipelihara dan diakses. Kebutuhannya perlu dipetakan lebih dahulu.'], ['q' => 'Apakah aplikasi web harus dibuat dari nol?', 'a' => 'Tidak selalu. Kami dapat mengembangkan sistem baru atau memperbaiki aplikasi yang sudah ada jika fondasinya masih layak.'], ['q' => 'Bagaimana memastikan aplikasi nyaman di mobile?', 'a' => 'Flow dan komponen dirancang responsif lalu diuji pada ukuran layar dan skenario penggunaan yang relevan.']],
                'portfolio_terms' => ['Web', 'POS', 'Dashboard', 'Booking'],
            ],
            'en' => [
                'meta_title' => 'Business Web Application Development | Aldef Tech',
                'meta_description' => 'Responsive web applications for internal portals, operational dashboards, customer services, and business workflows.',
                'eyebrow' => 'Web Application', 'title' => 'Web applications that make work easier to reach.', 'accent' => 'From the browser.',
                'lead' => 'Build a portal, dashboard, or operational application that works comfortably on desktop and mobile without adding friction for the team.',
                'pain_points' => ['Internal tools are hard to use when teams work on the move.', 'Important information takes too many steps to find.', 'The experience changes from one device to another.'],
                'capabilities' => ['Responsive UX flows and interfaces', 'Role-aware dashboards', 'API-first backends and data integrations', 'Performance, security, and basic observability'],
                'benefits' => ['More flexible access to work', 'Clearer navigation for each role', 'Room for further integrations and automation', 'A maintainable web foundation'],
                'process' => ['Understand users and devices', 'Design the main flows and data model', 'Build the core components and integrations', 'Test real scenarios and release in stages'],
                'technologies' => ['Laravel / PHP', 'Vue.js / React', 'Tailwind CSS', 'PostgreSQL / MySQL', 'REST / GraphQL'],
                'faq' => [['q' => 'Can a web application replace desktop software?', 'a' => 'For many business processes, web applications are easier to maintain and access. The fit should be assessed first.'], ['q' => 'Does a web application have to start from scratch?', 'a' => 'Not always. We can extend an existing system when its foundation is still suitable.'], ['q' => 'How do you make it comfortable on mobile?', 'a' => 'Flows and components are designed responsively and tested against relevant screen sizes and usage scenarios.']],
                'portfolio_terms' => ['Web', 'POS', 'Dashboard', 'Booking'],
            ],
        ],
        'saas-development' => [
            'id' => [
                'meta_title' => 'Jasa SaaS Development untuk Produk Digital | Aldef Tech',
                'meta_description' => 'Jasa SaaS development untuk membangun produk digital multi-tenant dengan billing, onboarding, akses pengguna, dan fondasi yang siap dikembangkan.',
                'eyebrow' => 'SaaS Development', 'title' => 'Bangun produk digital yang siap dipakai banyak pelanggan.', 'accent' => 'Tenant demi tenant.',
                'lead' => 'Kami membantu startup dan perusahaan merancang SaaS dari validasi MVP hingga platform yang terstruktur, dengan perhatian pada isolasi data dan operasional produk.',
                'pain_points' => ['MVP belum memiliki fondasi tenant dan role yang jelas.', 'Onboarding pelanggan masih bergantung pada pekerjaan manual.', 'Fitur baru berisiko mengganggu pelanggan yang sudah aktif.'],
                'capabilities' => ['Tenant, user, role, dan permission model', 'Subscription, billing, dan webhook integration', 'Onboarding, provisioning, dan admin console', 'Product analytics yang tidak mengekspos data pelanggan'],
                'benefits' => ['Struktur produk lebih mudah dipahami', 'Perubahan fitur dapat dirilis lebih terkontrol', 'Administrasi pelanggan lebih konsisten', 'Ruang tumbuh dari MVP ke versi berikutnya'],
                'process' => ['Validasi persona, use case, dan batas MVP', 'Rancang tenancy, billing, dan permission', 'Bangun core product dan admin tools', 'Uji onboarding, upgrade, dan edge cases'],
                'technologies' => ['Laravel / Node.js', 'Vue.js / React', 'PostgreSQL', 'Redis dan queues', 'Payment gateway API'],
                'faq' => [['q' => 'Apakah SaaS harus langsung memiliki semua fitur?', 'a' => 'Tidak. MVP yang fokus membantu memvalidasi alur utama sebelum investasi fitur diperluas.'], ['q' => 'Bagaimana data antar tenant dipisahkan?', 'a' => 'Model isolasi ditentukan sejak arsitektur dan diuji bersama role, query, serta akses administrasi.'], ['q' => 'Apakah billing bisa memakai gateway yang sudah ada?', 'a' => 'Bisa dipertimbangkan melalui API dan webhook gateway yang sesuai dengan kebutuhan produk.']],
                'portfolio_terms' => ['Cloud', 'SaaS', 'Drive', 'Platform'],
            ],
            'en' => [
                'meta_title' => 'SaaS Product Development | Aldef Tech',
                'meta_description' => 'SaaS development for multi-tenant digital products with billing, onboarding, user access, and a foundation built to evolve.',
                'eyebrow' => 'SaaS Development', 'title' => 'Build a digital product ready for many customers.', 'accent' => 'Tenant by tenant.',
                'lead' => 'We help startups and companies design SaaS from MVP validation to a structured platform, with care for data isolation and product operations.',
                'pain_points' => ['The MVP has no clear tenant or role foundation.', 'Customer onboarding still depends on manual work.', 'New features risk disrupting active customers.'],
                'capabilities' => ['Tenant, user, role, and permission models', 'Subscription, billing, and webhook integrations', 'Onboarding, provisioning, and admin consoles', 'Product analytics without exposing customer data'],
                'benefits' => ['A product structure that is easier to reason about', 'More controlled feature releases', 'Consistent customer administration', 'Room to move from MVP to the next version'],
                'process' => ['Validate personas, use cases, and MVP boundaries', 'Design tenancy, billing, and permissions', 'Build the core product and admin tools', 'Test onboarding, upgrades, and edge cases'],
                'technologies' => ['Laravel / Node.js', 'Vue.js / React', 'PostgreSQL', 'Redis and queues', 'Payment gateway APIs'],
                'faq' => [['q' => 'Does SaaS need every feature from day one?', 'a' => 'No. A focused MVP validates the core flow before feature investment expands.'], ['q' => 'How is data separated between tenants?', 'a' => 'The isolation model is designed at architecture level and tested with roles, queries, and administration access.'], ['q' => 'Can billing use an existing gateway?', 'a' => 'It can be considered through the gateway APIs and webhooks that fit the product requirements.']],
                'portfolio_terms' => ['Cloud', 'SaaS', 'Drive', 'Platform'],
            ],
        ],
        'ai-development' => [
            'id' => [
                'meta_title' => 'Jasa AI Development untuk Perusahaan | Aldef Tech',
                'meta_description' => 'Jasa AI development untuk knowledge base, chatbot, AI agent, ekstraksi dokumen, dan workflow yang terhubung dengan sistem perusahaan.',
                'eyebrow' => 'AI Development', 'title' => 'AI yang terhubung ke pekerjaan nyata, bukan sekadar demo.', 'accent' => 'Dengan kontrol.',
                'lead' => 'Kami membantu perusahaan memilih use case AI yang masuk akal, menyiapkan konteks data, dan mengintegrasikannya ke workflow yang dapat diawasi.',
                'pain_points' => ['Pengetahuan tim tersebar di dokumen dan percakapan.', 'Proses menjawab atau memeriksa dokumen memakan waktu.', 'Eksperimen AI belum memiliki batas akses dan evaluasi yang jelas.'],
                'capabilities' => ['Knowledge base dan retrieval workflow', 'AI assistant atau agent dengan tool terkontrol', 'OCR dan ekstraksi data dokumen', 'Guardrail, logging, dan human review'],
                'benefits' => ['Informasi lebih mudah ditemukan oleh tim', 'Pekerjaan awal dapat dibantu tanpa menghapus kontrol manusia', 'Use case dapat diuji dengan ruang lingkup yang jelas', 'Integrasi mengikuti sistem dan kebijakan perusahaan'],
                'process' => ['Pilih use case dan batas risiko', 'Audit sumber data dan kualitas konteks', 'Prototipe, evaluasi, lalu integrasikan', 'Pantau output dan perbaiki workflow secara berkala'],
                'technologies' => ['Python / FastAPI', 'LLM API', 'Vector search', 'OCR dan document pipeline', 'Laravel / REST API'],
                'faq' => [['q' => 'Apakah AI bisa mengakses semua data perusahaan?', 'a' => 'Tidak. Akses sebaiknya dibatasi berdasarkan kebutuhan, peran, dan kebijakan keamanan yang disepakati.'], ['q' => 'Bagaimana mengurangi jawaban AI yang keliru?', 'a' => 'Gunakan sumber yang terkurasi, instruksi yang jelas, evaluasi, logging, dan jalur review manusia untuk kasus penting.'], ['q' => 'Use case apa yang cocok untuk tahap awal?', 'a' => 'Use case yang berulang, memiliki konteks yang cukup, dan dapat diukur kualitasnya tanpa mengambil keputusan berisiko tinggi secara mandiri.']],
                'portfolio_terms' => ['AI', 'Chatbot', 'Attendance'],
            ],
            'en' => [
                'meta_title' => 'AI Development for Companies | Aldef Tech',
                'meta_description' => 'AI development for knowledge bases, chatbots, AI agents, document extraction, and workflows connected to company systems.',
                'eyebrow' => 'AI Development', 'title' => 'AI connected to real work, not just a demo.', 'accent' => 'With control.',
                'lead' => 'We help companies choose practical AI use cases, prepare the data context, and integrate them into workflows people can supervise.',
                'pain_points' => ['Team knowledge is scattered across documents and conversations.', 'Answering or checking documents consumes valuable time.', 'AI experiments lack clear access boundaries and evaluation.'],
                'capabilities' => ['Knowledge bases and retrieval workflows', 'Controlled AI assistants or agents', 'OCR and document data extraction', 'Guardrails, logging, and human review'],
                'benefits' => ['Information is easier for teams to find', 'First-pass work gets assistance without removing human control', 'Use cases can be tested within a clear scope', 'Integrations respect company systems and policies'],
                'process' => ['Choose the use case and risk boundaries', 'Audit data sources and context quality', 'Prototype, evaluate, then integrate', 'Monitor output and improve the workflow'],
                'technologies' => ['Python / FastAPI', 'LLM APIs', 'Vector search', 'OCR and document pipelines', 'Laravel / REST APIs'],
                'faq' => [['q' => 'Can AI access all company data?', 'a' => 'No. Access should be limited by need, role, and agreed security policies.'], ['q' => 'How do you reduce incorrect AI answers?', 'a' => 'Use curated sources, clear instructions, evaluation, logging, and human review for important cases.'], ['q' => 'What is a good first AI use case?', 'a' => 'A repeatable use case with sufficient context and a quality signal, without handing high-risk decisions to an unsupervised system.']],
                'portfolio_terms' => ['AI', 'Chatbot', 'Attendance'],
            ],
        ],
        'business-automation' => [
            'id' => [
                'meta_title' => 'Business Automation Indonesia untuk Proses Operasional | Aldef Tech',
                'meta_description' => 'Business automation Indonesia untuk approval, notifikasi, pelaporan, dan pemindahan data antar sistem agar proses operasional lebih teratur.',
                'eyebrow' => 'Business Automation', 'title' => 'Kurangi pekerjaan berulang dengan workflow yang dapat ditelusuri.', 'accent' => 'Satu alur.',
                'lead' => 'Aldef Tech merancang automasi proses bisnis yang menghubungkan trigger, aturan, pengguna, dan sistem tanpa menghilangkan titik kontrol penting.',
                'pain_points' => ['Data yang sama diinput berulang pada beberapa sistem.', 'Approval terlambat karena status sulit dilihat.', 'Laporan rutin dibuat manual dan rawan terlewat.'],
                'capabilities' => ['Workflow approval dan task routing', 'Webhook, scheduler, dan notification', 'Sinkronisasi data antar aplikasi', 'Exception handling dan audit log'],
                'benefits' => ['Status pekerjaan lebih mudah dipantau', 'Hand-off antar tim memiliki jejak yang jelas', 'Pekerjaan rutin punya aturan yang konsisten', 'Pengecualian tetap dapat ditangani manusia'],
                'process' => ['Petakan hand-off dan keputusan manual', 'Pilih trigger, aturan, dan titik persetujuan', 'Bangun integrasi serta notifikasi', 'Uji skenario normal, gagal, dan pengecualian'],
                'technologies' => ['Laravel queues', 'REST API dan webhooks', 'Cron / scheduler', 'Redis', 'Email dan WhatsApp API sesuai kebutuhan'],
                'faq' => [['q' => 'Proses apa yang cocok diautomasi?', 'a' => 'Proses berulang dengan aturan cukup stabil, input yang jelas, dan konsekuensi yang dapat ditinjau.'], ['q' => 'Apakah semua approval harus otomatis?', 'a' => 'Tidak. Automasi dapat menyiapkan data dan mengarahkan tugas, sementara keputusan tertentu tetap memerlukan persetujuan manusia.'], ['q' => 'Bagaimana jika integrasi pihak ketiga gagal?', 'a' => 'Workflow perlu memiliki retry, pencatatan error, dan jalur tindak lanjut agar kegagalan tidak hilang tanpa jejak.']],
                'portfolio_terms' => ['Automation', 'Dashboard', 'POS'],
            ],
            'en' => [
                'meta_title' => 'Business Automation for Operations | Aldef Tech',
                'meta_description' => 'Business automation for approvals, notifications, reporting, and data movement between systems so operations stay organised.',
                'eyebrow' => 'Business Automation', 'title' => 'Reduce repetitive work with traceable workflows.', 'accent' => 'One flow.',
                'lead' => 'Aldef Tech designs business automation that connects triggers, rules, people, and systems without removing important control points.',
                'pain_points' => ['The same data is entered into several systems.', 'Approvals stall because status is difficult to see.', 'Routine reports are prepared manually and can be missed.'],
                'capabilities' => ['Approval workflows and task routing', 'Webhooks, schedules, and notifications', 'Data synchronisation between applications', 'Exception handling and audit logs'],
                'benefits' => ['Work status is easier to follow', 'Team hand-offs have a clear trail', 'Routine work follows consistent rules', 'Exceptions can still be handled by people'],
                'process' => ['Map hand-offs and manual decisions', 'Choose triggers, rules, and approvals', 'Build integrations and notifications', 'Test normal, failure, and exception cases'],
                'technologies' => ['Laravel queues', 'REST APIs and webhooks', 'Cron / scheduler', 'Redis', 'Email and WhatsApp APIs where appropriate'],
                'faq' => [['q' => 'What processes are good candidates for automation?', 'a' => 'Repeatable processes with stable rules, clear inputs, and outcomes that can be reviewed.'], ['q' => 'Should every approval be automated?', 'a' => 'No. Automation can prepare data and route tasks while important decisions remain with people.'], ['q' => 'What happens when a third-party integration fails?', 'a' => 'The workflow should include retries, error records, and a follow-up path so failures do not disappear.']],
                'portfolio_terms' => ['Automation', 'Dashboard', 'POS'],
            ],
        ],
        'system-integration' => [
            'id' => [
                'meta_title' => 'Jasa Integrasi API dan Sistem Perusahaan | Aldef Tech',
                'meta_description' => 'Jasa integrasi API untuk menghubungkan ERP, CRM, payment gateway, aplikasi internal, dan database agar data mengalir lebih konsisten.',
                'eyebrow' => 'System Integration', 'title' => 'Hubungkan sistem yang sudah dipakai tanpa kehilangan kendali data.', 'accent' => 'Terintegrasi.',
                'lead' => 'Kami merancang API dan middleware untuk mengurangi input ganda, menjaga kontrak data, serta membuat kegagalan integrasi lebih mudah ditangani.',
                'pain_points' => ['Sistem inti dan aplikasi pendukung menyimpan data yang tidak sinkron.', 'Tim bergantung pada ekspor-impor manual.', 'Integrasi lama sulit dipantau ketika terjadi error.'],
                'capabilities' => ['API contract dan middleware', 'Data mapping, sync, dan idempotency', 'Webhook, retry, dan error monitoring', 'Authentication dan access boundary'],
                'benefits' => ['Data lintas sistem memiliki alur yang lebih jelas', 'Pekerjaan pemindahan data berulang dapat dikurangi', 'Masalah integrasi lebih mudah ditelusuri', 'Fondasi siap untuk workflow berikutnya'],
                'process' => ['Inventarisasi sistem dan pemilik data', 'Tentukan contract, mapping, dan arah sinkronisasi', 'Bangun adapter dan penanganan error', 'Uji duplikasi, keterlambatan, dan pemulihan'],
                'technologies' => ['REST / GraphQL', 'Laravel / Node.js', 'PostgreSQL / MySQL', 'Queues dan webhooks', 'OAuth / token-based access'],
                'faq' => [['q' => 'Sistem apa yang dapat diintegrasikan?', 'a' => 'Sistem dengan API, webhook, ekspor terstruktur, atau akses database yang memang diizinkan pemiliknya.'], ['q' => 'Apakah integrasi berarti mengganti sistem lama?', 'a' => 'Tidak. Integrasi justru dapat menjadi langkah untuk menghubungkan sistem yang masih dibutuhkan.'], ['q' => 'Bagaimana menjaga data tidak masuk dua kali?', 'a' => 'Gunakan mapping, idempotency key, validasi, dan pencatatan status sinkronisasi yang sesuai.']],
                'portfolio_terms' => ['Integration', 'POS', 'Booking', 'Cloud'],
            ],
            'en' => [
                'meta_title' => 'API and System Integration Services | Aldef Tech',
                'meta_description' => 'API integration for ERP, CRM, payment gateways, internal applications, and databases so business data moves consistently.',
                'eyebrow' => 'System Integration', 'title' => 'Connect the systems you rely on without losing data control.', 'accent' => 'Integrated.',
                'lead' => 'We design APIs and middleware that reduce duplicate entry, protect data contracts, and make integration failures easier to handle.',
                'pain_points' => ['Core and supporting systems hold out-of-sync data.', 'Teams rely on manual exports and imports.', 'Legacy integrations are difficult to monitor when errors occur.'],
                'capabilities' => ['API contracts and middleware', 'Data mapping, sync, and idempotency', 'Webhooks, retries, and error monitoring', 'Authentication and access boundaries'],
                'benefits' => ['Clearer data flows across systems', 'Less repeated data movement', 'More traceable integration issues', 'A foundation for the next workflow'],
                'process' => ['Inventory systems and data owners', 'Define contracts, mappings, and sync direction', 'Build adapters and error handling', 'Test duplicates, delays, and recovery'],
                'technologies' => ['REST / GraphQL', 'Laravel / Node.js', 'PostgreSQL / MySQL', 'Queues and webhooks', 'OAuth / token-based access'],
                'faq' => [['q' => 'What systems can be integrated?', 'a' => 'Systems with an API, webhook, structured export, or database access explicitly permitted by their owner.'], ['q' => 'Does integration mean replacing the old system?', 'a' => 'No. Integration can connect systems that are still needed.'], ['q' => 'How do you prevent duplicate records?', 'a' => 'Use appropriate mapping, idempotency keys, validation, and sync status records.']],
                'portfolio_terms' => ['Integration', 'POS', 'Booking', 'Cloud'],
            ],
        ],
        'website-development' => [
            'id' => [
                'meta_title' => 'Jasa Website Perusahaan yang Cepat dan SEO-Friendly | Aldef Tech',
                'meta_description' => 'Jasa website perusahaan dengan struktur konten, technical SEO, dan CTA yang membantu pengunjung memahami layanan serta menghubungi bisnis.',
                'eyebrow' => 'Website Development', 'title' => 'Website perusahaan yang menjelaskan nilai bisnis dengan jelas.', 'accent' => 'Siap ditemukan.',
                'lead' => 'Bukan hanya tampilan. Kami membangun website yang rapi secara teknis, mudah dipahami pengunjung, dan memiliki jalur konsultasi yang jelas.',
                'pain_points' => ['Pengunjung belum cepat memahami layanan dan keunggulan bisnis.', 'Website terlihat baik tetapi sulit ditemukan atau lambat.', 'CTA tidak mengarahkan pengunjung ke langkah berikutnya.'],
                'capabilities' => ['Information architecture dan responsive UI', 'Technical SEO dan structured data', 'CMS untuk konten yang perlu diperbarui', 'Analytics event dan conversion-ready CTA'],
                'benefits' => ['Pesan bisnis lebih mudah dipahami', 'Fondasi konten lebih siap untuk pencarian organik', 'Pengelolaan halaman lebih praktis', 'Sumber lead dapat dianalisis dengan lebih baik'],
                'process' => ['Tentukan audiens, intent, dan struktur halaman', 'Rancang copy, UI, dan content model', 'Bangun, optimalkan aset, dan pasang tracking', 'Uji mobile, form, metadata, serta aksesibilitas'],
                'technologies' => ['Laravel / Blade', 'Tailwind CSS', 'Vite', 'JSON-LD', 'GA4 atau GTM sesuai setup'],
                'faq' => [['q' => 'Apakah website bisa terhubung ke CMS?', 'a' => 'Bisa, jika kebutuhan konten dan peran editor memang memerlukannya. Struktur dibuat agar pembaruan tetap terkontrol.'], ['q' => 'Apakah SEO dijamin langsung berada di halaman pertama?', 'a' => 'Tidak ada jaminan peringkat. Fokusnya adalah fondasi teknis, konten relevan, dan pengalaman pengguna yang sehat.'], ['q' => 'Apakah CTA WhatsApp dan form bisa diukur?', 'a' => 'Bisa, dengan event tracking yang memisahkan intent klik dan submission yang benar-benar berhasil.']],
                'portfolio_terms' => ['Website', 'Web', 'Booking'],
            ],
            'en' => [
                'meta_title' => 'Fast, SEO-Friendly Company Website Development | Aldef Tech',
                'meta_description' => 'Company websites with clear content structure, technical SEO, and calls to action that help visitors understand and contact your business.',
                'eyebrow' => 'Website Development', 'title' => 'A company website that makes business value clear.', 'accent' => 'Ready to be found.',
                'lead' => 'More than a visual layer. We build a website that is technically sound, easy to understand, and clear about the next consultation step.',
                'pain_points' => ['Visitors do not quickly understand the service or business value.', 'The site looks good but is difficult to find or slow to load.', 'Calls to action do not guide visitors to the next step.'],
                'capabilities' => ['Information architecture and responsive UI', 'Technical SEO and structured data', 'CMS for content that needs updating', 'Analytics events and conversion-ready CTAs'],
                'benefits' => ['A clearer business message', 'A stronger foundation for organic discovery', 'Practical content management', 'Better visibility into lead sources'],
                'process' => ['Define audience, intent, and page structure', 'Design copy, UI, and content model', 'Build, optimise assets, and add tracking', 'Test mobile, forms, metadata, and accessibility'],
                'technologies' => ['Laravel / Blade', 'Tailwind CSS', 'Vite', 'JSON-LD', 'GA4 or GTM as configured'],
                'faq' => [['q' => 'Can the website connect to a CMS?', 'a' => 'Yes, when content and editor roles need it. The structure keeps updates controlled.'], ['q' => 'Can SEO rankings be guaranteed?', 'a' => 'No ranking can be guaranteed. The focus is a sound technical foundation, relevant content, and healthy user experience.'], ['q' => 'Can WhatsApp and form actions be measured?', 'a' => 'Yes, with events that separate click intent from successfully processed submissions.']],
                'portfolio_terms' => ['Website', 'Web', 'Booking'],
            ],
        ],
        'it-consulting' => [
            'id' => [
                'meta_title' => 'IT Consulting dan Konsultasi Arsitektur Sistem | Aldef Tech',
                'meta_description' => 'IT consulting untuk audit arsitektur, pemilihan teknologi, roadmap digital, keamanan aplikasi, dan keputusan sistem yang lebih terarah.',
                'eyebrow' => 'IT Consulting', 'title' => 'Kejelasan teknis sebelum investasi sistem diperbesar.', 'accent' => 'Dengan dasar.',
                'lead' => 'Dapatkan sudut pandang teknis yang terhubung ke tujuan operasional, baik sebelum membangun sistem baru maupun saat sistem lama mulai menjadi hambatan.',
                'pain_points' => ['Keputusan teknologi dibuat sebelum kebutuhan bisnis dipahami.', 'Roadmap digital terlalu luas untuk diprioritaskan.', 'Tim internal membutuhkan review arsitektur atau second opinion.'],
                'capabilities' => ['Architecture dan technology assessment', 'Process-to-system roadmap', 'Security dan maintainability review', 'Technical advisory untuk tim internal'],
                'benefits' => ['Prioritas teknis lebih mudah dijelaskan', 'Risiko keputusan awal dapat dibahas lebih cepat', 'Tim memiliki artefak untuk melanjutkan pekerjaan', 'Investasi sistem terhubung ke kebutuhan nyata'],
                'process' => ['Dengarkan tujuan dan kendala organisasi', 'Review sistem, proses, dan artefak yang tersedia', 'Susun temuan, opsi, dan trade-off', 'Berikan roadmap yang dapat ditindaklanjuti'],
                'technologies' => ['Web architecture', 'API dan integration patterns', 'Database design', 'Cloud / deployment review', 'Security fundamentals'],
                'faq' => [['q' => 'Apakah konsultasi hanya untuk perusahaan besar?', 'a' => 'Tidak. Lingkup dapat disesuaikan untuk perusahaan, SME, atau startup yang perlu membuat keputusan teknis lebih terarah.'], ['q' => 'Apakah harus melanjutkan development dengan Aldef Tech?', 'a' => 'Tidak. Hasil konsultasi dapat menjadi bahan kerja untuk tim internal atau partner engineering pilihan Anda.'], ['q' => 'Apa bentuk output konsultasi?', 'a' => 'Bentuknya mengikuti scope, misalnya temuan, opsi arsitektur, prioritas, risiko, dan roadmap implementasi.']],
                'portfolio_terms' => ['System', 'ERP', 'Dashboard', 'Cloud'],
            ],
            'en' => [
                'meta_title' => 'IT Consulting and System Architecture Advisory | Aldef Tech',
                'meta_description' => 'IT consulting for architecture reviews, technology choices, digital roadmaps, application security, and clearer system decisions.',
                'eyebrow' => 'IT Consulting', 'title' => 'Technical clarity before your system investment grows.', 'accent' => 'Grounded decisions.',
                'lead' => 'Get technical perspective connected to operational goals, whether you are planning a new system or an existing one is becoming a constraint.',
                'pain_points' => ['Technology decisions are made before the business need is understood.', 'The digital roadmap is too broad to prioritise.', 'An internal team needs an architecture review or second opinion.'],
                'capabilities' => ['Architecture and technology assessment', 'Process-to-system roadmaps', 'Security and maintainability reviews', 'Technical advisory for internal teams'],
                'benefits' => ['Technical priorities are easier to explain', 'Early decision risks are discussed sooner', 'Teams receive artifacts they can act on', 'System investment stays tied to real needs'],
                'process' => ['Understand organisational goals and constraints', 'Review systems, processes, and available artifacts', 'Set out findings, options, and trade-offs', 'Deliver an actionable implementation roadmap'],
                'technologies' => ['Web architecture', 'API and integration patterns', 'Database design', 'Cloud / deployment review', 'Security fundamentals'],
                'faq' => [['q' => 'Is consulting only for large companies?', 'a' => 'No. The scope can fit a company, SME, or startup that needs clearer technical decisions.'], ['q' => 'Must development continue with Aldef Tech?', 'a' => 'No. The consultation output can support an internal team or another engineering partner.'], ['q' => 'What does the consultation produce?', 'a' => 'It depends on scope, such as findings, architecture options, priorities, risks, and an implementation roadmap.']],
                'portfolio_terms' => ['System', 'ERP', 'Dashboard', 'Cloud'],
            ],
        ],
    ],
];
