<?php

// Template / brand variables surfaced in the admin layout.
return [
  "creatorName" => "Aldef Tech",
  "creatorUrl" => "https://aldeftech.com",
  "templateName" => "Aldef Tech",
  "templateSuffix" => "Admin Console",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Panel administrasi Aldef Tech — kelola konten, portofolio, leads, dan pengaturan situs.",
  "templateKeyword" => "aldef tech, admin, cms",
  "licenseUrl" => "https://aldeftech.com",
  "livePreview" => "https://aldeftech.com",
  "productPage" => "https://aldeftech.com",
  "support" => "https://aldeftech.com/contact",
  "moreThemes" => "https://aldeftech.com",
  "ogTitle" => "Aldef Tech Admin Console",
  "ogImage" => "/images/aldef-tech-banner.png",
  "ogType" => "website",
  "documentation" => "https://aldeftech.com",
  "generator" => "",
  "changelog" => "https://aldeftech.com",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
];
